import Container from "@components/atoms/Container/Container";
import Heading from "@components/atoms/Heading/Heading";
import Featured from "@components/templates/Featured";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Headstart Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <div className={styles.title}>
            <Heading size={1}>A Next.js Starter File.</Heading>
            <p>
              Built using <a href="https://sass-lang.com/">SCSS</a>,{" "}
              <a href="https://github.com/css-modules/css-modules">
                CSS Modules
              </a>
              , <a href="https://storybook.js.org/">StoryBoard.js</a>,{" "}
              <a>Jest</a>, and{" "}
              <a href="https://www.framer.com/motion/">Framer-Motion.</a>
            </p>
          </div>
        </Container>
        <Featured />
      </main>
    </div>
  );
};

export default Home;
