import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import styles from "./index.module.scss";

import { motion } from "framer-motion";
import variants from "./index.motion";

// Components
import Heading from "@components/atoms/Heading/Heading";
import Featured from "@components/templates/Featured";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Headstart Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.div
          className={styles.title}
          variants={variants.bg}
          initial={"initial"}
          animate={"in"}
          exit={"out"}
        >
          <motion.div variants={variants.title}>
            <Heading size={1}>A Next.js Starter File.</Heading>
            <p>
              Configured for{" "}
              <a href="https://github.com/css-modules/css-modules">
                SCSS Modules
              </a>
              , <a href="https://storybook.js.org/"> StoryBoard</a>,
              <a href="https://jestjs.io/"> Jest</a>,
              <a href="https://playwright.dev/"> Playwright.js </a>
              and <a href="https://www.framer.com/motion/">Framer-Motion.</a>
            </p>
          </motion.div>
        </motion.div>
        <Featured />
        <div className={styles.spacer}></div>
      </main>
    </div>
  );
};

export default Home;
